name: deploy nexturl to vercel
on:
  pull_request:
    branches:
      - 'main'
    types: [closed]
jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #add env file to .env.local
      - name: Set Env Vars on Vercel Project
        uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: talkiesapp # project name in Vercel
          envVariableKeys: APP_SECRET,DATABASE_URL,MIGRATE_DATABASE_URL
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          TARGET_APP_SECRET: production
          TYPE_APP_SECRET: encrypted
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TARGET_DATABASE_URL: production
          TYPE_DATABASE_URL: encrypted
          MIGRATE_DATABASE_URL: ${{ secrets.MIGRATE_DATABASE_URL }}
          TARGET_MIGRATE_DATABASE_URL: production
          TYPE_MIGRATE_DATABASE_URL: encrypted
      # deploy app to vercel
      - name: deploy site to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORGID}}  #Required
          vercel-project-id: ${{ secrets.PROJECTID}}
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
